# init error
D GITLET_EXIST_ERROR "A Gitlet version-control system already exists in the current directory."
# add error
D ADD_NOFILE_ERROR "File does not exist."
# rm error
D RM_ERROR "No reason to remove the file."
# commit error
D EMPTY_COMMIT "No changes added to the commit."
D EMPTY_MSG "Please enter a commit message."
# find error
D NOT_FOUND "Found no commit with that message."
# branch error
D BRANCH_EXIST "A branch with that name already exists."
# rm-branch error
D BRANCH_NOT_EXIST "A branch with that name does not exist."
D RM_CUR_BRANCH "Cannot remove the current branch."
# checkout error
D NO_FILE "File does not exist in that commit."
D NO_COMMIT "No commit with that id exists."
D NO_BRANCH "No such branch exists."
D CUR_BRANCH "No need to checkout the current branch."
D DANGER "There is an untracked file in the way; delete it, or add and commit it first."
# reset error
# NO_COMMIT
# DANGER
# merge special cases and error
D CONFLICT "Encountered a merge conflict."
D ANCESTOR "Given branch is an ancestor of the current branch."
D FAST "Current branch fast-forwarded."
D UNCOMMITTED "You have uncommitted changes."
# BRANCH_NOT_EXIST
D SELF "Cannot merge a branch with itself."
# DANGER
